version: '3.8'  # Adicionar versão explícita

services:

  nginx:
    image: 'nginx:1.25-alpine'
    container_name: <SITE_NAME>-nginx
    expose:
      - '80'
      - '443'
    depends_on:
      - phpfpm
    networks:
      - sr-reverse-proxy
      - <SITE_NAME>-net
    environment:
      - NGINX_HOST=<SITE_URL>
      - SITE_ID=<labels>
    volumes:
      - './system:/var/www/html'
      - './config/nginx/server.conf:/etc/nginx/conf.d/common/_server.conf:ro'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=sr-reverse-proxy"
      - "traefik.http.routers.<labels>.rule=Host(`<SITE_URL>`)"
      - "traefik.http.routers.<labels>.tls=true"
      - "traefik.http.routers.<labels>.service=<labels>"
      - "traefik.http.services.<labels>.loadbalancer.server.port=80"  
      - "traefik.http.routers.<labels>.middlewares=<labels>-prefix"
      - "traefik.http.middlewares.<labels>-prefix.stripprefix.prefixes=/<labels>"
    
  phpfpm:
    build:
      context: .containers
      dockerfile: php-fpm
      args:
        PHP_IMAGE: <PHP_IMAGE>
        CALLING_USER: <USER_NAME>
        CALLING_UID: 1000
    image: <PHP_IMAGE>-<USER_NAME>
    container_name: <SITE_NAME>-phpfpm
    networks:
      - <SITE_NAME>-net
      - sr-public_network
    volumes:
      - './system:/var/www/html'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:ro'
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 
      - PHP_OPCACHE_REVALIDATE_FREQ=0
    user: "1000:1000"

networks:
  sr-reverse-proxy:
    external: true
    name: sr-reverse-proxy
  <SITE_NAME>-net:
    driver: bridge
  sr-public_network:
    external: true
    name: sr-public_network
